version: 1.0.{build}
skip_non_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
          {
            Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
          }
before_build:
- cmd: nuget restore
build:
  project: Mifir.Concat.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: '**\mifir-concat.*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: bntYUbKetr7QNS4OclxF0hv/ff5Sy9/U8pXZcpqG5pvFQmQJB3Qj80O+82V2YrGe
  skip_symbols: true
dotnet_csproj:
  patch: true
  file: '**\Mifir.Concat.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'