name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build and Pack with dotnet
      run: dotnet pack --configuration Release
    - name: Push Nuget Source
      run: dotnet nuget push "mifir-concat.1.0.0.nupkg"  -s "https://nuget.pkg.github.com/MCKanpolat/Mifir-Concat/index.json"
